# Generated by Django 4.1.5 on 2023-01-13 13:01

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='title field')),
                ('slug', models.SlugField(unique=True, verbose_name='slug field')),
                ('descr', models.TextField(blank=True, max_length=4096, verbose_name='description')),
                ('image', models.ImageField(upload_to=main.utils.upload_image, verbose_name='post image')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creating')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=64, unique=True, verbose_name='email field')),
                ('username', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='username field')),
                ('profile_image', models.ImageField(upload_to=main.utils.upload_user_profile_image, verbose_name='user profile image')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='date when user join us')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
