# Generated by Django 4.1.5 on 2023-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
    ]
