# Generated by Django 4.1.5 on 2023-01-14 22:09

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, unique=True, verbose_name='album name')),
                ('slug', models.SlugField(unique=True, verbose_name='album slug')),
                ('description', models.TextField(max_length=512, verbose_name='Album description')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utils.upload_albom_element_image, verbose_name='album image element')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album')),
            ],
        ),
    ]
