# Generated by Django 4.1.5 on 2023-02-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsitem_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumelement',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.album'),
        ),
    ]
